// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.smartclassrooms.grpc.user;

public interface APIResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:APIResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responsemessage = 1;</code>
   */
  java.lang.String getResponsemessage();
  /**
   * <code>string responsemessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponsemessageBytes();

  /**
   * <code>int32 responseCode = 2;</code>
   */
  int getResponseCode();
}
