// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.smartclassrooms.grpc.user;

public interface RegisterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RegisterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
