// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: qanda.proto

package com.smartclassrooms.grpc.qanda;

public interface QuestionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Question)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string question_text = 2;</code>
   */
  java.lang.String getQuestionText();
  /**
   * <code>string question_text = 2;</code>
   */
  com.google.protobuf.ByteString
      getQuestionTextBytes();
}
