// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exam.proto

package com.smartclassrooms.grpc.exam;

public interface SubmissionConfirmationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SubmissionConfirmation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string submissionresponse = 1;</code>
   */
  java.lang.String getSubmissionresponse();
  /**
   * <code>string submissionresponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getSubmissionresponseBytes();

  /**
   * <code>int32 responseCode = 2;</code>
   */
  int getResponseCode();
}
