// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: qanda.proto

package com.smartclassrooms.grpc.qanda;

public interface AnswerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Answer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string answer_text = 2;</code>
   */
  java.lang.String getAnswerText();
  /**
   * <code>string answer_text = 2;</code>
   */
  com.google.protobuf.ByteString
      getAnswerTextBytes();
}
