// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: qanda.proto

package com.smartclassrooms.grpc.qanda;

public interface AnswerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Answer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response = 1;</code>
   */
  java.lang.String getResponse();
  /**
   * <code>string response = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseBytes();
}
