// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: qanda.proto

package com.smartclassrooms.grpc.qanda;

public interface QuestionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Question)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request = 1;</code>
   */
  java.lang.String getRequest();
  /**
   * <code>string request = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestBytes();
}
