// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exam.proto

package com.smartclassrooms.grpc.exam;

public interface AssignmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Assignment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string coursename = 2;</code>
   */
  java.lang.String getCoursename();
  /**
   * <code>string coursename = 2;</code>
   */
  com.google.protobuf.ByteString
      getCoursenameBytes();
}
