// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exam.proto

package com.smartclassrooms.grpc.exam;

/**
 * Protobuf type {@code Grade}
 */
public  final class Grade extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Grade)
    GradeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Grade.newBuilder() to construct.
  private Grade(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Grade() {
    grade_ = 0;
    assignmentname_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Grade(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            grade_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            assignmentname_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.smartclassrooms.grpc.exam.Exam.internal_static_Grade_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.smartclassrooms.grpc.exam.Exam.internal_static_Grade_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.smartclassrooms.grpc.exam.Grade.class, com.smartclassrooms.grpc.exam.Grade.Builder.class);
  }

  public static final int GRADE_FIELD_NUMBER = 1;
  private int grade_;
  /**
   * <code>int32 grade = 1;</code>
   */
  public int getGrade() {
    return grade_;
  }

  public static final int ASSIGNMENTNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object assignmentname_;
  /**
   * <code>string assignmentname = 2;</code>
   */
  public java.lang.String getAssignmentname() {
    java.lang.Object ref = assignmentname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      assignmentname_ = s;
      return s;
    }
  }
  /**
   * <code>string assignmentname = 2;</code>
   */
  public com.google.protobuf.ByteString
      getAssignmentnameBytes() {
    java.lang.Object ref = assignmentname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      assignmentname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (grade_ != 0) {
      output.writeInt32(1, grade_);
    }
    if (!getAssignmentnameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, assignmentname_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (grade_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, grade_);
    }
    if (!getAssignmentnameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, assignmentname_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.smartclassrooms.grpc.exam.Grade)) {
      return super.equals(obj);
    }
    com.smartclassrooms.grpc.exam.Grade other = (com.smartclassrooms.grpc.exam.Grade) obj;

    boolean result = true;
    result = result && (getGrade()
        == other.getGrade());
    result = result && getAssignmentname()
        .equals(other.getAssignmentname());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + GRADE_FIELD_NUMBER;
    hash = (53 * hash) + getGrade();
    hash = (37 * hash) + ASSIGNMENTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getAssignmentname().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.smartclassrooms.grpc.exam.Grade parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartclassrooms.grpc.exam.Grade parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartclassrooms.grpc.exam.Grade parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartclassrooms.grpc.exam.Grade parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartclassrooms.grpc.exam.Grade parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartclassrooms.grpc.exam.Grade parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartclassrooms.grpc.exam.Grade parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smartclassrooms.grpc.exam.Grade parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smartclassrooms.grpc.exam.Grade parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.smartclassrooms.grpc.exam.Grade parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smartclassrooms.grpc.exam.Grade parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smartclassrooms.grpc.exam.Grade parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.smartclassrooms.grpc.exam.Grade prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Grade}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Grade)
      com.smartclassrooms.grpc.exam.GradeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smartclassrooms.grpc.exam.Exam.internal_static_Grade_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smartclassrooms.grpc.exam.Exam.internal_static_Grade_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smartclassrooms.grpc.exam.Grade.class, com.smartclassrooms.grpc.exam.Grade.Builder.class);
    }

    // Construct using com.smartclassrooms.grpc.exam.Grade.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      grade_ = 0;

      assignmentname_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.smartclassrooms.grpc.exam.Exam.internal_static_Grade_descriptor;
    }

    @java.lang.Override
    public com.smartclassrooms.grpc.exam.Grade getDefaultInstanceForType() {
      return com.smartclassrooms.grpc.exam.Grade.getDefaultInstance();
    }

    @java.lang.Override
    public com.smartclassrooms.grpc.exam.Grade build() {
      com.smartclassrooms.grpc.exam.Grade result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.smartclassrooms.grpc.exam.Grade buildPartial() {
      com.smartclassrooms.grpc.exam.Grade result = new com.smartclassrooms.grpc.exam.Grade(this);
      result.grade_ = grade_;
      result.assignmentname_ = assignmentname_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.smartclassrooms.grpc.exam.Grade) {
        return mergeFrom((com.smartclassrooms.grpc.exam.Grade)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.smartclassrooms.grpc.exam.Grade other) {
      if (other == com.smartclassrooms.grpc.exam.Grade.getDefaultInstance()) return this;
      if (other.getGrade() != 0) {
        setGrade(other.getGrade());
      }
      if (!other.getAssignmentname().isEmpty()) {
        assignmentname_ = other.assignmentname_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.smartclassrooms.grpc.exam.Grade parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.smartclassrooms.grpc.exam.Grade) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int grade_ ;
    /**
     * <code>int32 grade = 1;</code>
     */
    public int getGrade() {
      return grade_;
    }
    /**
     * <code>int32 grade = 1;</code>
     */
    public Builder setGrade(int value) {
      
      grade_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 grade = 1;</code>
     */
    public Builder clearGrade() {
      
      grade_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object assignmentname_ = "";
    /**
     * <code>string assignmentname = 2;</code>
     */
    public java.lang.String getAssignmentname() {
      java.lang.Object ref = assignmentname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        assignmentname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string assignmentname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAssignmentnameBytes() {
      java.lang.Object ref = assignmentname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        assignmentname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string assignmentname = 2;</code>
     */
    public Builder setAssignmentname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      assignmentname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string assignmentname = 2;</code>
     */
    public Builder clearAssignmentname() {
      
      assignmentname_ = getDefaultInstance().getAssignmentname();
      onChanged();
      return this;
    }
    /**
     * <code>string assignmentname = 2;</code>
     */
    public Builder setAssignmentnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      assignmentname_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Grade)
  }

  // @@protoc_insertion_point(class_scope:Grade)
  private static final com.smartclassrooms.grpc.exam.Grade DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.smartclassrooms.grpc.exam.Grade();
  }

  public static com.smartclassrooms.grpc.exam.Grade getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Grade>
      PARSER = new com.google.protobuf.AbstractParser<Grade>() {
    @java.lang.Override
    public Grade parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Grade(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Grade> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Grade> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.smartclassrooms.grpc.exam.Grade getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

