// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exam.proto

package com.smartclassrooms.grpc.exam;

public interface GradeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Grade)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 grade = 1;</code>
   */
  int getGrade();

  /**
   * <code>string assignmentname = 2;</code>
   */
  java.lang.String getAssignmentname();
  /**
   * <code>string assignmentname = 2;</code>
   */
  com.google.protobuf.ByteString
      getAssignmentnameBytes();
}
